server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yqz66/my-springcloud-config.git
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/